### ISSUE TITLE
Cannot Start a Chat with Given History

### ISSUE THREAD

**Issue by Co1lin** [google/generative-ai-docs#228]
### Description of the bug:

Hi, I want to start a conversation using `ChatSession` with some given histories, such as:

```python
import google.generativeai as genai

model = genai.GenerativeModel('gemini-pro')

chat = model.start_chat(history=[
    {
        'role': 'user',
        'parts': ['You are a helpful assistant.']
    },
    {
        'role': 'model',
        'parts': ['Sure.'],
    },
])


resp = chat.send_message(
    content='hi, how are you?',
)

print(resp.text)
```

However, the program above threw an exception pasted below:

```python
Traceback (most recent call last):
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.65.234:443 {created_time:"2024-01-18T22:37:41.46318178-05:00", grpc_status:13, grpc_message:"An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/code/some_proj/test.py", line 18, in <module>
    resp = chat.send_message(
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 367, in send_message
    response = self.model.generate_content(
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 248, in generate_content
    response = self._client.generate_content(request)
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 566, in generate_content
    response = rpc(
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/data/miniforge3/envs/py310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 77, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InternalServerError: 500 An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting
```

What's the right way to start a conversation with some history? Thanks!

**Comment by nattametee007** [comment]
same too

**Comment by Co1lin** [comment]
I realized that the problem is the `history` parameter only accepts a list of google defined history objects, but not the list of dicts I provided above. It's not working in the similar way as OpenAI's interface. But I think it's better to support such style because constructing that google defined objects is not easy.

**Comment by MarkDaoust** [comment]
Hi @Co1lin, thanks for the report. 

That should totally work.

This line runs the history through `to_contents`

https://github.com/google/generative-ai-python/blob/main/google/generativeai/generative_models.py#L306C43-L306C78

Which handles the conversion of any acceptable thing into a list of `glm.Content` objects. Here:

https://github.com/google/generative-ai-python/blob/main/google/generativeai/types/content_types.py#L225

I just copied your code into colab and it works:

![Screenshot from 2024-02-08 13-12-40](https://github.com/google/generative-ai-docs/assets/1414837/0dd9dec6-e7dd-40b5-a35f-e3f42b2bc14c)


There have been intermittent 500 errors. Maybe that's what you hit. Try again?

**Comment by MoseDien** [comment]
I'm good to run this code.

**Comment by Himanshu-Adhikari** [comment]
what if everytime i want to have a new conversation then what should i do

**Comment by BryceBlankinship** [comment]
@Himanshu-Adhikari you would just initialize the start_chat function without providing the history array.

**Comment by Himanshu-Adhikari** [comment]
@BryceBlankinship  thank you for your suggestion
