### ISSUE TITLE
PaLM: Error trying to use python API

### ISSUE THREAD

**Issue by pentney** [google/generative-ai-docs#63]
When trying to use the google-generativeai library in python, I get the following error trying to import:

Traceback (most recent call last):
  File "palm_summarizer.py", line 3, in <module>
    import google.generativeai as palm
  File "/home/bill/.local/lib/python3.8/site-packages/google/generativeai/__init__.py", line 59, in <module>
    from google.generativeai import types
  File "/home/bill/.local/lib/python3.8/site-packages/google/generativeai/types/__init__.py", line 19, in <module>
    from google.generativeai.types.text_types import *
  File "/home/bill/.local/lib/python3.8/site-packages/google/generativeai/types/text_types.py", line 34, in <module>
    class Completion(abc.ABC):
  File "/home/bill/.local/lib/python3.8/site-packages/google/generativeai/types/text_types.py", line 49, in Completion
    filters: Optional[list[safety_types.ContentFilterDict]]
TypeError: 'type' object is not subscriptable

I'm using Python 3.8; couldn't find a required version in the docs. Does it require a different version? Or is something else wrong here?

**Comment by markmcd** [comment]
Python 3.9 is the minimum supported version, however we accidentally released a package (`0.1.0rc2`) that required 3.9, but was marked as supporting 3.8. So, if you installed `google-generativeai` in a 3.8 environment, you'd get the broken package.

I've just yanked `0.1.0rc2` from PyPI, so this should no longer be an issue. 3.8 users will get an old package, but at least now it works.

I'll add a badge to the repo to indicate that 3.9 is the min supported version, too.

**Comment by markmcd** [comment]
I think we've done everything we can here. The bad package was yanked & the [Python repo](https://github.com/google/generative-ai-python#readme) shows the supported Python versions. Feel free to reopen if you think I've missed something.
